import sys
from manual_parser import (
    read_csv_manual,
    convert_types,
    calculate_summary,
    write_json as write_json_manual
)

from pandas_parser import (
    read_csv_pandas,
    calculate_summary_pandas,
    write_json as write_json_pandas
)

def main():
    csv_file = sys.argv[1]
    rows = read_csv_manual(csv_file)
    rows = convert_types(rows)
    manual_summary = calculate_summary(rows)
    write_json_manual(
        manual_summary,
        "task_3/output/manual_summary.json"
    )
    df = read_csv_pandas(csv_file)
    pandas_summary = calculate_summary_pandas(df)
    write_json_pandas(
        pandas_summary,
        "task_3/output/pandas_summary.json"
    )
    with open("task_3/output/comparison_report.md", "w") as file:
        file.write("Comparison Report\n\n")
        file.write("The summaries generated by the manual CSV parser and the pandas parser were compared.\n\n")

        if manual_summary == pandas_summary:
            file.write("Result: Both summaries match exactly.\n")
            file.write("This shows that the manual parser produces the same output as the pandas implementation.\n")
        else:
            file.write("Result: The summaries do not match.\n")
            file.write("The generated JSON files should be inspected to identify the differences.\n")

if __name__ == "__main__":
    main()